version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:80"
#  db:
#    build:
#      context: ./
#      dockerfile: postgres/Dockerfile
#    volumes:
#      - postgres_data:/var/lib/postgres/data
#    ports:
#      - "5432:5432"
#  nginx:
#    build:
#      context: ./
#      dockerfile: ./nginx/Dockerfile
#    ports:
#      - "80:80"
volumes:
  postgres_data: